### ISSUE TITLE
Not sure your sort requirements make sense

### ISSUE THREAD

**Issue by raymatos** [nolanlawson/pouchdb-find#137]
So lets take the following dataset

```js
{
_id: id
name: string,
age: int
location: string
}
```

in SQL you could do something like this

```
select id, name from table where name like "somename" order by age asc;
```

I wouldnt be able to do something like this in pouchdb.find

Doing

```
db.find({
  selector : { name: "something"},
  fields: ['_id','name'],
  sort: ['age']
})
```

Will yield the following error ```Error: conflicting sort and selector fields```

So i tried this

```
db.find({
  selector : { name: "something", age : {"$exists" : true}},
  fields: ['_id','name'],
  sort: ['age']
})
```
Then it complains saying that i can only use 
```
couldn't find a usable index. try creating an index on: name, age. Make sure that only $eq, $gt, $gte, $lt, and $lte are used for the indexed fields.
```

Here is the 2 indexes i tried using
```
index: {
   fields: ['name', 'age']
}
index: {
   fields: ['name']
}
```

I come from a mysql background and i know this pattern is from mongoDB, so maybe i just dont understand it.

**Comment by nolanlawson** [comment]
No, you're right, this is a design flaw in Mango. I too think it's silly that you need to sort on exactly the field that you search for. It should just run the query and do the sort in-memory if necessary.

Unfortunately this is not something that we can solve, since the goal of `pouchdb-find` is to implement Mango exactly as designed. I suggest opening a ticket on https://github.com/cloudant/mango.
