### ISSUE TITLE
Size of the library

### ISSUE THREAD

**Issue by ronyrun** [nolanlawson/pouchdb-find#166]
Hello, 

I'm using a cordova application with this lib and the command : bower install pouchdb-find

Install a package of 2,50 MB.
Is there a way to reduce the size (with getting rid of the www folder in the bower lib)? 

This is impacting strongly the cordova mobile app size

Regards, 
Ron

**Comment by froatsnook** [comment]
Use webpack!

**Comment by nolanlawson** [comment]
Please use npm instead of bower. Bower makes it very difficult for me to slim down the size of packages, because it is basically just a thin layer over Git.

Nearly every Node open-source project is currently migrating from Bower to npm (including Ionic), so please use npm and thus the future-safe bet. :)
