### ISSUE TITLE
$text temporary alternative

### ISSUE THREAD

**Issue by natcohen** [nolanlawson/pouchdb-find#167]
$text is not available and it might take some time (https://github.com/nolanlawson/pouchdb-find/issues/141) so I was wondering if we could come up with a temporary solution. Instead of looking in the text, would it be possible to create $any which would look into all the fields?

Just throwing the idea, I don't even know if it's possible...

**Comment by colinskow** [comment]
Right now you can use [PouchDB Quick Search](https://github.com/nolanlawson/pouchdb-quick-search), although it doesn't integrate with find.

I don't think it would be too difficult to wire that plugin to $text search.

**Comment by nolanlawson** [comment]
I think given the size and complexity of `$text` and the fact that it can never really match what Mango is doing, I think it's better to just say that pouchdb-find will not support it.

We could maybe write a version of pouchdb-find in the future that pulls in pouchdb-quick-search and wraps `$text` around it, but I would move that to a separate module because of the file size increase.

**Comment by colinskow** [comment]
My main use case is to first narrow down the documents that need to be full-text searched with `pouchdb-find`, and then perform a query on those. So `pouchdb-find` would perform a query on the selector, output a list of doc_ids and pass those to `pouchdb-quick-find`.

I could write a plugin to pair the two, but it may require small tweaks to either engine.
