### ISSUE TITLE
Very slow queries on ~20k documents

### ISSUE THREAD

**Issue by refrigerator** [nolanlawson/pouchdb-find#207]
My local database has about just under 20k documents and I'm trying to run simple queries using `pouchdb.find()`. The query time seems to be very long though - just searching on one field at a time using `$eq`, it took 7 seconds on field A and 40 seconds (!) on field B, with indexes having already been created for both these fields.

Am I doing something wrong here?

**Comment by nolanlawson** [comment]
Probably not; queries in pouchdb-find are just very slow due to the overhead of creating a second PouchDB database. Unless it gives you a `warning` in the output object about the indexes you created, meaning it's not actually using the index and is instead doing it all in-memory (after reading the entire database into memory)?

**Comment by refrigerator** [comment]
Ah okay. No - no warnings about indexes. Do you have any ideas for how to speed these queries up? If my understanding is correct, using normal map/reduce views won't be any quicker than Pouchdb-find, right?

**Comment by nolanlawson** [comment]
Yeah they are both basically the same under the hood.

One way to speed it up is to use multiple PouchDBs instead of a single one. E.g. break them up by type. This allows IndexedDB to parallelize operations under the hood, and avoids the overhead of the map/reduce indexer scanning a lot of documents that don't `emit()` anything.

Another way is to use another database besides PouchDB for your querying (such as an in-memory one like LokiJS or even just regular JavaScript arrays) because in general PouchDB is good at syncing but not so good at querying.

**Comment by refrigerator** [comment]
Great, thanks! Querying using `array.filter` takes a few milliseconds on 20k docs and doesn't seem to hog up too much memory so I think we'll just use javascript for now.

**Comment by garrensmith** [comment]
I'm closing this ticket
