### ISSUE TITLE
CouchDB 2.0 Support

### ISSUE THREAD

**Issue by ronag** [nolanlawson/pouchdb-find#221]
Can this be used against CouchDB 2.0?

**Comment by EuAndreh** [comment]
Sure!

Just to clear confusions: pouchdb-find is the PouchDB equivalent of [CouchDB's Mango](https://github.com/cloudant/mango), which means that is was created with the purpose to maintain compatibility with CouchDB.

You can use it with CouchDB 2.0 or a Cloudant database. If you use pouchdb-find with CouchDB 1.x, you'll be able to you it also, but only to sync the data: since Mango was added only on 2.0, you can do a remote query, something like:
```javascript
let db = PouchDB('http://localhost:5984/mydb');
db.find({
  selector: {
    ...
  }
})
```

This can be done with Cloudant or CouchDB 2.0, not with CouchDB 1.x.

**Comment by garrensmith** [comment]
That is correct. Pouchdb-find is a plugin to pouchdb. So pouchdb will
replicate with an old CouchDB 1.x but you cannot run a mango query against
it.

**Comment by garrensmith** [comment]
It works with CouchDB 2.0

All misspelling thanks to my iPhone.




On Tue, Oct 25, 2016 at 11:44 PM +0200, "Robert Nagy" <notifications@github.com> wrote:












Can this be used against CouchDB 2.0?
