### ISSUE TITLE
Dealilng with Dates

### ISSUE THREAD

**Issue by BigBlueHat** [nolanlawson/pouchdb-find#235]
I work with a good bit of JSON and JSON-LD that use ISO 8601 as the date storage format. When I create indexes in Map/Reduce, I turn the dates into arrays and get these lovely "complex key" indexes where I can group by year, month, day, etc.

I've not been able to sort (heh) how to do that in pouchdb-find/CouchDB mango/Cloudant query since there's no way (that I've found at least) to state that the "string value of this key is a date."

Am I missing something obvious? or is this a feature that just doesn't exist in this descriptive query syntax (yet)?

Thanks!
🎩

**Comment by nolanlawson** [comment]
The typical way of dealing with this is to use e.g. `new Date().toISOString()` and then do normal lexicographical string comparisons with `$lt` and `$gt`... however I agree it's not very ergonomic.

Looking at [the Mango documentation](https://github.com/cloudant/mango) it doesn't appear to have any concept of a Date, and furthermore this would be difficult to represent in JSON since JSON also doesn't have Dates. Hence I think the string solution is probably the best workaround even if it's a bit icky.

**Comment by BigBlueHat** [comment]
Thanks @nolanlawson. I'll do more digging on that front, and see what I discover.

Consider this closed...for now. :wink:

**Comment by numerized** [comment]
Hi there

I use too new Date().toISOString() for all my dates.

But I can't sort with this parameter.

THIS WORKS :
```
selector: {type:{$eq: 'userAssessment'}, upliftId:{$eq: upliftId}, createdAt:{$gt:null}},
sort: [{type: 'desc'}]
```

THIS DOESN'T :
```
selector: {type:{$eq: 'userAssessment'}, upliftId:{$eq: upliftId}, createdAt:{$gt:null}},
sort: [{createdAt: 'desc'}]
```

my index is : 

```
        this.db[this.upliftId].createIndex({
          index: {
            fields: ['type', 'createdAt', 'upliftId']
          }
        })
```

Any question welcome I'm going to use unix timestamps and report then.

**Comment by numerized** [comment]
The workaround I've found is the following:

```
        this.db[this.upliftId].find({
            selector: {type:{$eq: 'userAssessment'}, createdAt:{$gt: null}, upliftId:{$eq: upliftId}},
            sort: [{type:'desc'}, {createdAt:'desc'}, {upliftId:'desc'}]
        })
```
