### ISSUE TITLE
Dynamic Key

### ISSUE THREAD

**Issue by akircher** [nolanlawson/pouchdb-find#52]
Hi Nolan,

Thanks again for the awesome work on PouchDB and various plugins.  I have a question, I am trying to migrate my map/reduces to `find()` and I am having trouble finding objects with dynamic keys.

For example
```
{ history: { dynamicKey1:1, dynamicKey2:2 }}
{ history: { dynamicKey3:3, dynamicKey4:4 }}
{ history: { dynamicKey5:5, dynamicKey1:1 }}
```

I can't create an index on each dynamic key because there are thousands of them.  Rightfully the below asks for an index
```
db.find({
  selector: { 'history.dynamicKey1': { $exists:true }},
})
```
The following does not, but fails with an error

```
db.find({
  selector: { history:{ dynamicKey1: { $exists:true }}},
})
```

Will finding a `dynamicKey` in an object be possible using PouchDB find?  Will `$elemMatch` help here? Or do I need to restructure my data?  If so what's the best structure?

Thanks
Adam

**Comment by nolanlawson** [comment]
Dynamic keys ought to be possible (the "fails with an error" you mention sounds like a bug), but since you'd have to create an index for every possible dynamic key, I think it would be terribly inefficient in pouchb-find.

Your best bet, in my opinion, would be either to use map/reduce (since it's much more flexible than pouchdb-find), or restructure your data so that the keys are not dynamic. Else yes, `$elemMatch` would help you in that case, but I don't know when I'll have time to implement it. :stuck_out_tongue:

**Comment by garrensmith** [comment]
v0.7.0 now has `$elemMatch` support. So I'm now closing this.
